/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package v1_pro;
import AppPackage.AnimationClass;
import java.awt.Color;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import v1_pro.Classes.Art_work;
import v1_pro.Classes.Customer;
import v1_pro.Classes.Gallery;
import v1_pro.Classes.User;
/**
 *
 * @author Noran
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public  Gallery g;
    AnimationClass AC=new AnimationClass();
    public Main()
    {
        initComponents();
        try{
        preProcessor();
        }catch(Exception e){}
        
        this.setLocationRelativeTo(null);
        SlideShow();
    }
     private void SlideShow()
    {
        new Thread(new Runnable()
        {
            int count;
            
            public void run()
            {   
                try
                {
                    while(true)
                    {
                        switch(count)                            
                        {
                            case 0:
                                ImageIcon i1=new ImageIcon(getClass().getResource("/BackgroundImages/1.jpg"));
                                Slide1.setIcon(i1);       
                                Thread.sleep(3000);
                                AC.jLabelXLeft(0, -850, 20, 7,Slide1);
                                AC.jLabelXLeft(850, 0, 20, 7, Slide2);
                                //AC.jLabelXLeft(1700,850, 20, 7, Slide3);
                                count=1;
                                break;
                                
                            case 1:
                                ImageIcon i2=new ImageIcon(getClass().getResource("/BackgroundImages/3.jpg"));
                                Slide2.setIcon(i2);    
                                Thread.sleep(3000);
                                AC.jLabelXRight(-850, 0, 20, 7,Slide1);
                                AC.jLabelXRight(0, 850, 20, 7, Slide2);
                               // AC.jLabelXLeft(850,0, 20, 7, Slide3);
                                count=2;
                                break;
                             
                            case 2:
                               ImageIcon i3=new ImageIcon(getClass().getResource("/BackgroundImages/7.jpg"));
                                Slide1.setIcon(i3);       
                                Thread.sleep(3000);
                                AC.jLabelXLeft(0, -850, 20, 7,Slide1);
                                AC.jLabelXLeft(850, 0, 20, 7, Slide2);
                                //AC.jLabelXLeft(1700,850, 20, 7, Slide3);
                                count=3;
                                break; 
                                
                            case 3:
                                ImageIcon i4=new ImageIcon(getClass().getResource("/BackgroundImages/2.jpg"));
                                Slide2.setIcon(i4);    
                                Thread.sleep(3000);
                                AC.jLabelXRight(-850, 0, 20, 7,Slide1);
                                AC.jLabelXRight(0, 850, 20, 7, Slide2);
                               // AC.jLabelXLeft(850,0, 20, 7, Slide3);
                                count=0;
                                break; 
                                
                        }
                        
                           
                                  
                    }
                }
                catch(Exception e)
                {
            
                }
            }
        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        User_btn = new javax.swing.JButton();
        Admin_btn = new javax.swing.JButton();
        Slide1 = new javax.swing.JLabel();
        Slide2 = new javax.swing.JLabel();
        Slide3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(850, 550));
        setName("MainFrame"); // NOI18N
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(850, 550));
        setSize(new java.awt.Dimension(850, 550));
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(51, 110, 123));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Art Gallery");

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("-");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("x");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(438, 438, 438)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)))
                        .addGap(0, 24, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 874, 91);

        jPanel3.setBackground(new java.awt.Color(44, 62, 80));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        User_btn.setBackground(new java.awt.Color(51, 110, 123));
        User_btn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        User_btn.setForeground(new java.awt.Color(255, 255, 255));
        User_btn.setText("USER");
        User_btn.setName("User_btn"); // NOI18N
        User_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                User_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                User_btnMouseExited(evt);
            }
        });
        User_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                User_btnActionPerformed(evt);
            }
        });
        jPanel3.add(User_btn);

        Admin_btn.setBackground(new java.awt.Color(51, 110, 123));
        Admin_btn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Admin_btn.setForeground(new java.awt.Color(255, 255, 255));
        Admin_btn.setText("ADMIN");
        Admin_btn.setBorder(null);
        Admin_btn.setMaximumSize(new java.awt.Dimension(119, 45));
        Admin_btn.setMinimumSize(new java.awt.Dimension(119, 45));
        Admin_btn.setName("Admin_btn"); // NOI18N
        Admin_btn.setPreferredSize(new java.awt.Dimension(119, 45));
        Admin_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Admin_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Admin_btnMouseExited(evt);
            }
        });
        Admin_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin_btnActionPerformed(evt);
            }
        });
        jPanel3.add(Admin_btn);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 465, 850, 100);

        Slide1.setBackground(new java.awt.Color(44, 62, 80));
        Slide1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackgroundImages/1.jpg"))); // NOI18N
        Slide1.setInheritsPopupMenu(false);
        Slide1.setMaximumSize(new java.awt.Dimension(850, 380));
        Slide1.setMinimumSize(new java.awt.Dimension(850, 380));
        Slide1.setPreferredSize(new java.awt.Dimension(850, 380));
        getContentPane().add(Slide1);
        Slide1.setBounds(0, 100, 850, 360);

        Slide2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackgroundImages/3.jpg"))); // NOI18N
        Slide2.setMaximumSize(new java.awt.Dimension(850, 380));
        Slide2.setMinimumSize(new java.awt.Dimension(850, 380));
        Slide2.setPreferredSize(new java.awt.Dimension(850, 380));
        getContentPane().add(Slide2);
        Slide2.setBounds(850, 100, 850, 360);

        Slide3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackgroundImages/7.jpg"))); // NOI18N
        Slide3.setMaximumSize(new java.awt.Dimension(850, 315));
        Slide3.setMinimumSize(new java.awt.Dimension(850, 315));
        Slide3.setPreferredSize(new java.awt.Dimension(850, 315));
        getContentPane().add(Slide3);
        Slide3.setBounds(1700, 100, 850, 315);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        System.exit(0);

    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void Admin_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin_btnActionPerformed
        // TODO add your handling code here:
        AdminLogin1 alg=new AdminLogin1();
        alg.show();
        this.hide();
    }//GEN-LAST:event_Admin_btnActionPerformed

    private void User_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_User_btnActionPerformed
        // TODO add your handling code here:
         LoginForm lg=new LoginForm();
         lg.show();
         this.hide();
    }//GEN-LAST:event_User_btnActionPerformed

    private void Admin_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Admin_btnMouseEntered
        // TODO add your handling code here:
        //Admin_btn.setBackground(51,110,123);
        Admin_btn.setBackground(Color.GRAY);
        
    }//GEN-LAST:event_Admin_btnMouseEntered

    private void Admin_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Admin_btnMouseExited
        // TODO add your handling code here:
        Admin_btn.setBackground(Color.getColor("336E7B"));
        
    }//GEN-LAST:event_Admin_btnMouseExited

    private void User_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_User_btnMouseEntered
        // TODO add your handling code here:
        User_btn.setBackground(Color.GRAY);
    }//GEN-LAST:event_User_btnMouseEntered

    private void User_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_User_btnMouseExited
        // TODO add your handling code here:
         User_btn.setBackground(Color.getColor("336E7B"));
    }//GEN-LAST:event_User_btnMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Admin_btn;
    private javax.swing.JLabel Slide1;
    private javax.swing.JLabel Slide2;
    private javax.swing.JLabel Slide3;
    private javax.swing.JButton User_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables

    void preProcessor() throws FileNotFoundException{
      Scanner  x=new Scanner(new File("User.txt"));
      boolean found= false;
            while(x.hasNext())
            { 
             String fName=x.next(),lName=x.next(),UserName=x.next(),Password=x.next(),Telephone=x.next(),Address=x.next();
               // System.out.println(x.next());
               g.AddUser(new Customer(Address,0,UserName,Password));
                             // g.AddUser(new Customer("",0,"",""));

        }
        x = new Scanner(new File("artworks.txt"));
        while (x.hasNext() && !found) {
            String ID = x.next(), Year = x.next(), Title = x.next(), TOA = x.next(), Price = x.next(), photo = x.next(), phot2 = x.next(), photo3 = x.next();
            System.out.println(ID + " " + Year + " " + Title + " " + TOA + " " + Price + " " + photo+" "+phot2+" "+photo3);
            if (phot2 == ".") {
                g.AddArt(new Art_work(Integer.parseInt(ID), Year, Title, TOA, Integer.parseInt(Price), photo));
            } else {
                g.AddArt(new Art_work(Integer.parseInt(ID), Year, Title, TOA, Integer.parseInt(Price), photo, phot2, photo3));
            }
        }

           
    }
   
}
